### ISSUE TITLE
Feature/Search Population

### ISSUE THREAD

**Issue by thereeling** [MarkCyg/Yafoodle#10]
As a USER,
I WANT to see a list of recipes after I initiate a search.
SO THAT I can select a recipe and get more information.

**Comment by thereeling** [comment]
GIVEN  I search for a recipe,
WHEN I click the search button,
THEN I am presented with a list of 5 random recipes that fit my search criteria.

Recipe selection is looking good, just need to work on the HTML render(what's going in the element, buttons, links etc.)

**Comment by JPDBrodeur** [comment]
Good news is that I've already done the heavy lifting on getting results to render. I'll work on pushing this as soon as I can today.

**Comment by JPDBrodeur** [comment]
Got 'em!
