### ISSUE TITLE
Feature/Localstorage

### ISSUE THREAD

**Issue by thereeling** [MarkCyg/Yafoodle#9]
As a USER,
I WANT, to see a list of my recent searches.
SO THAT, when I click a searched item, YaFoodle will search for that clicked item.

**Comment by JPDBrodeur** [comment]
Everything is in place. The issue is with the event listener not being able to listen for dynamically created content. I have had some success this morning researching possible alternatives so I'll continue working to get this closed.

**Comment by JPDBrodeur** [comment]
After getting the Dynamic Listener to work on DOM elements appended after page load, we can officially consider this closed!
